services:
  - type: web
    name: todo-app
    env: php
    plan: free
    branch: main
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t ."
    autoDeploy: true
    envVars:
      - key: PHP_VERSION
        value: "8.1"
